---
- name: Install docker package dependencies
  ansible.builtin.package:
    name: '{{ docker_packages }}'
    state: present
  become: true
  register: install_docker_packages
  when: docker_packages is defined
  tags:
    - docker-install
