---
- include: include_vars.yml

- include: dependences.yml

- include: install.yml

- include: permissions.yml
  when: docker_users | length > 0

- include: post_install.yml
  when: docker_install_compose | bool
