---
- include_tasks: include_vars.yml

- name: Update apt cache.
  apt: update_cache=yes force_apt_get=yes
  when: ansible_os_family == 'Debian'

- include_tasks: dependences.yml

- include_tasks: install.yml

- include_tasks: permissions.yml
  when: docker_users | length > 0

- include_tasks: post_install.yml
  when: docker_install_compose | bool
