---
- name: validate docker-compose
  block:
    - name: Check current docker-compose version.
      command: '{{ docker_compose_path }} --version'
      register: docker_compose_current_version
      changed_when: false
      failed_when: false

- name: install docker-compose
  block:
    - name: Delete existing docker-compose version if it's different.
      file:
        path: '{{ docker_compose_path }}'
        state: absent
      when: >
        docker_compose_current_version.stdout is defined
        and docker_compose_version not in docker_compose_current_version.stdout

    - name: install docker-compose
      block:
        - name: Install Docker Compose (if configured).
          get_url:
            url: '{{ docker_compose_url }}'
            dest: '{{ docker_compose_path }}'
            mode: 0755
      when:
        - >
          docker_compose_current_version.stdout is not defined or docker_compose_version
          not in docker_compose_current_version.stdout
        - ansible_architecture != "aarch64" and ansible_architecture != "armv7l"

    - name: Install docker-compose on ARM
      block:
        - name: include os specific variables for architecture
          include_vars: '{{ ansible_architecture | lower }}.yml'
          with_first_found:
            - '{{ ansible_architecture | lower }}.yml'
            - 'main.yml'
          tags:
            - 'docker'
            - 'docker-vars'

        - name: Install Docker Compose (if configured).
          get_url:
            url: '{{ docker_compose_url }}'
            dest: '{{ docker_compose_path }}'
            mode: 0755
      when:
        - >
          docker_compose_current_version.stdout is not defined or docker_compose_version
          not in docker_compose_current_version.stdout
        - ansible_architecture == "aarch64" or ansible_architecture == "armv7l"
