---
- name: Ensure old versions of Docker are not installed.
  package:
    name:
      - docker
      - docker-engine
    state: absent

- name: Ensure dependencies are installed.
  apt:
    name:
      - apt-transport-https
      - ca-certificates
    state: present

- name: Return installed docker
  ansible.builtin.command: which docker
  register: docker

- name: Install docker.
  block:
    - name: download docker
      get_url:
        url: https://get.docker.com
        force: true
        dest: /tmp/get-docker.sh
        mode: "0100"

    - name: install docker
      ansible.builtin.command: /tmp/get-docker.sh

    - name: newgrp docker
      ansible.builtin.command: newgrp docker
  when: not docker
