---
- name: Converge
  hosts: all
  become: true

  pre_tasks:
    - name: Update apt cache.
      apt: update_cache=yes cache_valid_time=600
      when: ansible_os_family == 'Debian'

  roles:
    - role: hadenlabs.docker

  vars:
    docker_install_compose: true
    docker_compose_version: '1.29.0'
